// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.FileSecurity.Client
{
    using Models;
    using System.IO;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for InternalClient.
    /// </summary>
    internal static partial class InternalClientExtensions
    {
            /// <summary>
            /// Creates/Uploads a certificate for a specific subscription.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The subscription that owns the certificate.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='certificatePassword'>
            /// </param>
            public static CertificateResponse CreateCertificates(this IInternalClient operations, System.Guid subscriptionId, string name, Stream certificate, string certificatePassword = default(string))
            {
                return operations.CreateCertificatesAsync(subscriptionId, name, certificate, certificatePassword).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates/Uploads a certificate for a specific subscription.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The subscription that owns the certificate.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='certificatePassword'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CertificateResponse> CreateCertificatesAsync(this IInternalClient operations, System.Guid subscriptionId, string name, Stream certificate, string certificatePassword = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateCertificatesWithHttpMessagesAsync(subscriptionId, name, certificate, certificatePassword, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get details of the requested certificate managed by a subscrition.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The subscription that owns the certificate.
            /// </param>
            /// <param name='certificateId'>
            /// Identifier of the certificate to fetch.
            /// </param>
            public static CertificateResponse GetCertificates(this IInternalClient operations, System.Guid subscriptionId, System.Guid certificateId)
            {
                return operations.GetCertificatesAsync(subscriptionId, certificateId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get details of the requested certificate managed by a subscrition.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The subscription that owns the certificate.
            /// </param>
            /// <param name='certificateId'>
            /// Identifier of the certificate to fetch.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CertificateResponse> GetCertificatesAsync(this IInternalClient operations, System.Guid subscriptionId, System.Guid certificateId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetCertificatesWithHttpMessagesAsync(subscriptionId, certificateId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Update certificate and details
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The subscription that owns the certificate
            /// </param>
            /// <param name='certificateId'>
            /// Identifier of the certificate to update.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='certificatePassword'>
            /// </param>
            public static CertificateResponse UpdateCertificates(this IInternalClient operations, System.Guid subscriptionId, System.Guid certificateId, string name, Stream certificate, string certificatePassword = default(string))
            {
                return operations.UpdateCertificatesAsync(subscriptionId, certificateId, name, certificate, certificatePassword).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update certificate and details
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The subscription that owns the certificate
            /// </param>
            /// <param name='certificateId'>
            /// Identifier of the certificate to update.
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='certificatePassword'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CertificateResponse> UpdateCertificatesAsync(this IInternalClient operations, System.Guid subscriptionId, System.Guid certificateId, string name, Stream certificate, string certificatePassword = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.UpdateCertificatesWithHttpMessagesAsync(subscriptionId, certificateId, name, certificate, certificatePassword, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete requested certificate managed by a subscrition.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The subscription that owns the certificate.
            /// </param>
            /// <param name='certificateId'>
            /// Identifier of the certificate to delete.
            /// </param>
            public static void DeleteCertificates(this IInternalClient operations, System.Guid subscriptionId, System.Guid certificateId)
            {
                operations.DeleteCertificatesAsync(subscriptionId, certificateId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete requested certificate managed by a subscrition.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// The subscription that owns the certificate.
            /// </param>
            /// <param name='certificateId'>
            /// Identifier of the certificate to delete.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteCertificatesAsync(this IInternalClient operations, System.Guid subscriptionId, System.Guid certificateId, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteCertificatesWithHttpMessagesAsync(subscriptionId, certificateId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
