// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.FileSecurity.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateCertificateResponse
    {
        /// <summary>
        /// Initializes a new instance of the CreateCertificateResponse class.
        /// </summary>
        public CreateCertificateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateCertificateResponse class.
        /// </summary>
        public CreateCertificateResponse(System.Guid? certificateId = default(System.Guid?), string name = default(string))
        {
            CertificateId = certificateId;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "certificateId")]
        public System.Guid? CertificateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
