// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.FileSecurity.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PdfPrivilegeModelSignConfigurationCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PdfPrivilegeModelSignConfigurationCreateRequest class.
        /// </summary>
        public PdfPrivilegeModelSignConfigurationCreateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PdfPrivilegeModelSignConfigurationCreateRequest class.
        /// </summary>
        public PdfPrivilegeModelSignConfigurationCreateRequest(string name = default(string), string ownerPassword = default(string), System.Guid? certificateId = default(System.Guid?), PdfPrivilegeModel privileges = default(PdfPrivilegeModel))
        {
            Name = name;
            OwnerPassword = ownerPassword;
            CertificateId = certificateId;
            Privileges = privileges;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ownerPassword")]
        public string OwnerPassword { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "certificateId")]
        public System.Guid? CertificateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "privileges")]
        public PdfPrivilegeModel Privileges { get; set; }

    }
}
