// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.FileSecurity.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PdfPrivilegeModel
    {
        /// <summary>
        /// Initializes a new instance of the PdfPrivilegeModel class.
        /// </summary>
        public PdfPrivilegeModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PdfPrivilegeModel class.
        /// </summary>
        public PdfPrivilegeModel(int? copyAllowLevel = default(int?), int? changeAllowLevel = default(int?), bool? allowAssembly = default(bool?), bool? allowScreenReaders = default(bool?), bool? allowFillIn = default(bool?), bool? allowModifyAnnotations = default(bool?), bool? allowCopy = default(bool?), bool? allowModifyContents = default(bool?), bool? allowDegradedPrinting = default(bool?), bool? allowPrint = default(bool?), int? printAllowLevel = default(int?), bool? allowAll = default(bool?), bool? forbidAll = default(bool?))
        {
            CopyAllowLevel = copyAllowLevel;
            ChangeAllowLevel = changeAllowLevel;
            AllowAssembly = allowAssembly;
            AllowScreenReaders = allowScreenReaders;
            AllowFillIn = allowFillIn;
            AllowModifyAnnotations = allowModifyAnnotations;
            AllowCopy = allowCopy;
            AllowModifyContents = allowModifyContents;
            AllowDegradedPrinting = allowDegradedPrinting;
            AllowPrint = allowPrint;
            PrintAllowLevel = printAllowLevel;
            AllowAll = allowAll;
            ForbidAll = forbidAll;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "copyAllowLevel")]
        public int? CopyAllowLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "changeAllowLevel")]
        public int? ChangeAllowLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowAssembly")]
        public bool? AllowAssembly { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowScreenReaders")]
        public bool? AllowScreenReaders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowFillIn")]
        public bool? AllowFillIn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowModifyAnnotations")]
        public bool? AllowModifyAnnotations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowCopy")]
        public bool? AllowCopy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowModifyContents")]
        public bool? AllowModifyContents { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowDegradedPrinting")]
        public bool? AllowDegradedPrinting { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowPrint")]
        public bool? AllowPrint { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "printAllowLevel")]
        public int? PrintAllowLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowAll")]
        public bool? AllowAll { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "forbidAll")]
        public bool? ForbidAll { get; set; }

    }
}
