// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.FileSecurity.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SignConfigurationPdfResponse
    {
        /// <summary>
        /// Initializes a new instance of the SignConfigurationPdfResponse
        /// class.
        /// </summary>
        public SignConfigurationPdfResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SignConfigurationPdfResponse
        /// class.
        /// </summary>
        public SignConfigurationPdfResponse(System.Guid? id = default(System.Guid?), string name = default(string), System.Guid? certificateId = default(System.Guid?), System.Guid? subscriptionId = default(System.Guid?), System.DateTime? createdDate = default(System.DateTime?), PdfPrivilegeModel pdfPrivilege = default(PdfPrivilegeModel), string certificateRawData = default(string))
        {
            Id = id;
            Name = name;
            CertificateId = certificateId;
            SubscriptionId = subscriptionId;
            CreatedDate = createdDate;
            PdfPrivilege = pdfPrivilege;
            CertificateRawData = certificateRawData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "certificateId")]
        public System.Guid? CertificateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pdfPrivilege")]
        public PdfPrivilegeModel PdfPrivilege { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "certificateRawData")]
        public string CertificateRawData { get; set; }

    }
}
